# Generated by Django 4.0.3 on 2022-03-04 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PreRest', '0002_alter_preguntas_respuesta_alter_preguntas_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuesta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
