# Generated by Django 4.0.3 on 2022-03-04 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PreRest', '0004_remove_preguntas_respuesta_respuesta_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='fechadecreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='fechadecreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
